### ISSUE TITLE
SPEC license?

### ISSUE THREAD

**Issue by jloizu** [PrincetonUniversity/SPEC#191]
I don't see any license associated with SPEC. We should make one. All authors/contributors should agree on a license type, including, I guess, our respective institutions. 

For example, STELLOPT has an MIT license, and SIMSOPT has an L-GPL/GPL license (both open-source, but with different restrictions).

Stuart, can you explain what is your or PPPL's take on this?

**Comment by jonathanschilling** [comment]
[choosealicense.com](https://choosealicense.com/) is a good point to start for figuring out what common licenses are available.

I guess the MIT license would be most appropriate for SPEC. It is also used for VMEC.
One could also consider the Apache 2.0 License, which asks for marking changes when distributing modified versions, which the MIT license does not ask for.
The GPL* licenses are a little bit problematic, since they ask for disclosing the source of any software that links to the GPL-licensed component. However, the term "to link to sth" is interpreted extremely strict in this context AFAIK. For example, any wrapper that creates input files for SPEC, runs the code, and reads its output, could be interpreted to "be linked with SPEC" and thus would need to be open-sourced as well.

**Comment by zhisong** [comment]
Academically speaking, there is not too much difference.

Would we be happy if some private company makes a stellarator optimisation suit out of the source code of SPEC, becomes closed-source, and sells it for a profit? GPL forbids that from happening (at least directly).

**Comment by zhucaoxiang** [comment]
I helped Stuart choose the GPL-v3 license long ago when we registered the DOE code page (https://www.osti.gov/doecode/biblio/12548). But I guess it could be updated if necessary.

**Comment by jloizu** [comment]
From this link, looks like SPEC has a GPL license, but this does not appear on the SPEC github repo, is it just a matter of indicating it then?

**Comment by zhisong** [comment]
I have added GPLv3.0 to the master branch to match the DOE code page.
